### ISSUE TITLE
hcaptcha has alignment issues causing ugly white background to show up in darkmode

### ISSUE THREAD

**Issue by tilkinsc** [hCaptcha/react-hcaptcha#225]
Reproduced on both edge and firefox. Version 1.10.1

![image](https://github.com/hCaptcha/react-hcaptcha/assets/7494772/d4522e27-4906-465a-8567-fb00a0a1299e)

```js
			<HCaptcha
				sitekey="10000000-ffff-ffff-ffff-000000000001"
				onVerify={(token, eKey) => 1}
				reCaptchaCompat={false}
				/>
```

I have dug into the html and it appears that the body of the iframe that gets injected is at fault. On the left, you can see me editing around with the style of the html as shown below. On the right thats the vanilla code you see above.
![image](https://github.com/hCaptcha/react-hcaptcha/assets/7494772/60bb1908-b7c7-49df-b6fb-6bf400b9f571)

I am using vite, bootstrap, and react-router-dom. This background doesn't seem respective to those being present. Proven by deleting all the css on the page, as shown below.
![image](https://github.com/hCaptcha/react-hcaptcha/assets/7494772/9e7f195d-41cf-4e64-86da-9f2077a5aaf1)

**Comment by zoryana94** [comment]
Hi @tilkinsc,

Thank you for notifying us about the issue!
We will keep you posted

Best Regards
hCaptcha Dev Team

**Comment by Red-Killer** [comment]
Yep got the same issue looks very ugly
![image](https://github.com/hCaptcha/react-hcaptcha/assets/59504268/bef74b88-b392-4c74-98a2-3c9e87ff305f)

**Comment by anilmawji** [comment]
This is still an issue. When will it be fixed? Since it's an iframe we are at hCaptcha's mercy when it comes to the styling..

**Comment by oyed** [comment]
@brdlyptrs  if this is completed can we get a new release please? the issue still persists as of the latest version available - thanks!

**Comment by brdlyptrs** [comment]
Hi @oyed! We've updated the core code to have a transparent background for both the body and html of the checkbox iFrame. If you are still seeing an issue, can you please provide some more details so that we can take a further look?

**Comment by VlldmrS** [comment]
![image](https://github.com/user-attachments/assets/9bb33c12-7a67-4543-862a-238aaec6dcb4)

The problem is still relevant, it spoils the design of the form

**Comment by VlldmrS** [comment]
Next 15, Turbopack, Chakra UI

**Comment by VlldmrS** [comment]
![image](https://github.com/user-attachments/assets/52908265-0b10-4279-be62-ecc93b448112)

The problem is on the iframe side. If you change the transparent background of the body to the one in the theme (for example, in my case, black), then the problem is eliminated.

**Comment by cordant-jd** [comment]
Only way I could fix this ugly white was to use max width/height

```typescript
<div className="flex items-center justify-center max-w-[298px] max-h-[72px] rounded-lg overflow-hidden">
  <HCaptcha
    sitekey={hCaptchaSiteKey}
    onVerify={onCaptchaChange}
    ref={captchaRef}
    onExpire={onCaptchaExpire}
    theme="dark"
  />
</div>
```

**Comment by zoryana94** [comment]
Hi @tilkinsc @cordant-jd @VlldmrS @devlsh @anilmawji @Red-Killer,
 
We added more changes. The issue should be completely fixed now.
Please check it out.

Best Regards,
hCaptcha Dev Team

**Comment by cordant-jd** [comment]
> We added more changes. The issue should be completely fixed now. Please check it out.

Sadly, the issue is still present.

`border-color: rgb(245, 245, 245);` even if `theme="dark"` is set.

**Comment by brdlyptrs** [comment]
Hi @cordant-jd,

We will see if we can adjust the border color to be more in alignment with the darker theme. However the current contrast was set to help with accessibility. If you are a Pro subscriber, the custom theme configuration will allow you to adjust this to your desired color palette. 

Best Regards,
hCaptcha Dev Team
